# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs: 
  node: circleci/node@5.0.2
  android: circleci/android@2.0.3
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    parameters:
      android-image:
        type: string
      node-version:
        type: string
      system-image:
        type: string
      avd:
        type: string
    machine:
      image: <<paramaters.android-image>>
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: <<paramaters.node-version>>
      - restore_cache:
          key: node-cache
      - run: npm install
      - save_cache:
          key: node-cache
          paths: 
            - node_modules
      - run: sdkmanager <<paramaters.system-image>>
      - run: echo "no" | avdmanager --verbose create avd -n <<paramaters.avd>> -k <<paramaters.system-image>>
      - run: emulator -list-avds
      - run: adb start-server
      - restore_cache:
          key: build-cache
      - run: cd android && ./gradlew assembleRelease --warning-mode=all #builds a release build
      - run: cd android/app/build/outputs/apk && ls
      - save_cache:
          key: build-cache
          paths: 
            - android/app/build/outputs/apk
      - run:
          command: |
            run_with_retry() {
                MAX_TRIES=2
                n=1
                until [ $n -gt $MAX_TRIES ]
                do
                  echo "Starting test attempt $n"
                  cd android && ./gradlew test && break
                  n=$[$n+1]
                  sleep 5
                done
                if [ $n -gt $MAX_TRIES ]; then
                  echo "Max tries reached (2)"
                  exit 1
                fi
            }
            run_with_retry
          name: Run tests with max tries of 2
      - run: cd android && ./gradlew test
      - run: cd android && ./gradlew connectedAndroidTest
      - run: cd __tests__ && ls
      - run: cd android/app/build && ls
      # - android/start-emulator-and-run-tests:
      #     run-tests-working-directory: android
      - store_test_results:
          path: android/app/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: android/app/build/test-results
          destination: artifact-file
      - store_artifacts:
          path: android/app/build/outputs/apk
          destination: build
      - run: emulator -avd <<paramaters.avd>> -no-window -no-audio -no-boot-anim -verbose -no-snapshot -gpu swiftshader_indirect
      
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              android-image: [android:2022.04.1, android:2022.01.1, android:2021.10.1]
              node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
              system-image: ["system-images;android-29;default;x86_64", "system-images;android-28;default;x86_64"]
              avd: ["avd1", "avd2", "avd3"]