# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs: 
  node: circleci/node@5.0.2
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '16.13'
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: npm install
      - run: ls
      # - run: sudo apt-get update && sudo apt-get install -y openjdk-8-jdk && sudo apt-get install -y ant && sudo apt-get clean;
      # - run: sudo apt-get update && sudo apt-get install ca-certificates-java && sudo apt-get clean && sudo update-ca-certificates -f;
      # # - run: ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/ RUN export JAVA_HOME
      # - run: vim ~/bash_profile export JAVA_HOME=/usr/sun/jdk/v1.6.0_16-64bit/ export PATH = $JAVA_HOME/bin:$PATH
      - run: java --version
      - run: cd android && ./gradlew assembleRelease

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello