version: 2.1

orbs: 
  node: circleci/node@5.0.2
  android: circleci/android@2.0.3
jobs:
  test:
    parameters:
      node-version: 
        type: string
      system-image: 
          type: string
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: << parameters.node-version >>
      - restore_cache:
          key: node-cache-{{ .BuildNum }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ .BuildNum }}
          paths: 
            - node_modules
      - run: sdkmanager "<<parameters.system-image>>"
      - run: echo "no" | avdmanager --verbose create avd -n avd1 -k "<<parameters.system-image>>"
      - run: adb start-server
      - run: 
          command: npx react-native run-android && yarn test && cd android && gradle test && adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done
          name: Run emulator, test, and kill
      - store_test_results:
          path: android/app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: android/app/build/test-results/testReleaseUnitTest
      - store_test_results:
          path: reports
  build:
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - restore_cache:
          key: node-cache-{{ .BuildNum }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ .BuildNum }}
          paths: 
            - node_modules
      - run: sdkmanager "system-images;android-29;default;x86_64"
      - run: echo "no" | avdmanager --verbose create avd -n avd1 -k "system-images;android-29;default;x86_64"
      - run: adb start-server
      - restore_cache:
          key: build-cache
      - run: rm -rf android/app/src/main/res/drawable-*
      # - run: 
      #     command: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      #     name: bundle android app
      - run: cd android && ./gradlew bundleRelease
      - save_cache:
          key: build-cache-{{ .BuildNum }}
          paths: 
            - android/app/build/outputs/bundle
      - store_artifacts:
          path: android/app/build/outputs/bundle
          destination: build
  deploy-internal:
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - run: fastlane run upload_to_play_store track:"internal"
  deploy-alpha:
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - run: fastlane run upload_to_play_store track:"alpha"
  deploy-beta:
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - run: fastlane run upload_to_play_store track:"beta"
  deploy-production:
    machine:
      image: android:2022.04.1
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - run: fastlane run upload_to_play_store 


      
workflows:
  build-and-test-workflow:
    jobs:
      - test:
         matrix:
            parameters:
               node-version: ["12.9.1", "13.9.0", "16.13.0"]
               system-image: ["system-images;android-29;default;x86_64", "system-images;android-28;default;x86_64", "system-images;android-29;default;x86", "system-images;android-28;default;x86"]
      - build:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-internal:
          filters:
            tags:
              only: /^internal-.*/
          # requires:
          #   - build
              #ex tag: internal-1.0.0
      - deploy-alpha:
          filters:
            tags:
              only: /^alpha-.*/
          # requires:
          #   - build
              #ex tag: alpha-1.0.0
      - deploy-beta:
          filters:
            tags:
              only: /^beta-.*/
          # requires:
          #   - build
              #ex tag: beta-1.0.0
      - deploy-production:
          filters:
            tags:
              only: /^release-.*/
          # requires:
          #   - build
              #ex tag: release-1.0.0
